"""Product branding constants (user-facing).

Internal env prefixes remain ``AI_CRASH_FIX_*`` for compatibility.
"""

from __future__ import annotations

from pathlib import Path
import sys

PRODUCT_NAME = "Fixora"
PRODUCT_NAME_LEGACY = "AI Crash Fix"
PRODUCT_SLUG = "fixora"
API_TITLE = f"{PRODUCT_NAME} API"
PR_BODY_FOOTER = f"\n\n---\n\n> **Generated by {PRODUCT_NAME}**\n"
PR_TITLE_PREFIX = f"{PRODUCT_NAME} PR: "
JIRA_SUMMARY_PREFIX = f"[{PRODUCT_NAME}]"
JIRA_MR_HEADING = f"h3. {PRODUCT_NAME} — Merge Request"
APP_BUNDLE_NAME = f"{PRODUCT_NAME}.app"
DMG_BASENAME = "Fixora"
MACOS_APP_SUPPORT_DIRNAME = PRODUCT_NAME
MACOS_APP_SUPPORT_DIRNAME_LEGACY = PRODUCT_NAME_LEGACY


def resolve_macos_application_support() -> Path:
    """Prefer Fixora Application Support; fall back to legacy folder if present."""
    home = Path.home()
    fixora = (home / "Library" / "Application Support" / MACOS_APP_SUPPORT_DIRNAME).resolve()
    legacy = (
        home / "Library" / "Application Support" / MACOS_APP_SUPPORT_DIRNAME_LEGACY
    ).resolve()
    if fixora.is_dir():
        return fixora
    if legacy.is_dir():
        return legacy
    return fixora


def default_data_dir_hint() -> str:
    if sys.platform == "darwin":
        return f"~/Library/Application Support/{MACOS_APP_SUPPORT_DIRNAME}/"
    return "(set AI_CRASH_FIX_DATA_DIR)"
